services:

  dwdforecast:
    image: dwdforecast:latest
    container_name: dwdforecast
    build:
      context: .
      dockerfile: ./Dockerfile
    hostname: dwdforecast
    restart: always
    volumes:
      - ./config/:/app/config:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - iot

networks:
  iot:
